version: "2"

formats: all

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.6"
  jobs:
    pre_build:
      - echo "Command run at 'pre_build' step"
      - sphinx-apidoc -Mf -o docs/source mini_toolbox/

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
